name: MAIN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 .  --max-line-length=130 --statistics --exclude test*
    - name: Test with pytest
      run: |
        pytest --doctest-modules --junitxml=test-report/test-results-${{ matrix.python-version }}.xml

#  deploy-to-prod:
#    needs: build
#    runs-on: ubuntu-latest
#  
#    steps:
#    - uses: actions/checkout@master
#    - name: SCP
#      uses: appleboy/scp-action@master
#      with:
#        host: ${{ secrets.PROD_HOST }}
#        username: ${{ secrets.USERNAME }}
#        port: ${{ secrets.PROD_PORT }}
#        password: ${{ secrets.PASSWORD }}
#        source: "."
#        target: "vyos_cfg_v2"
#        
#    - name: pip update
#      uses: garygrossgarten/github-action-ssh@release
#      with:
#        command: pip3 install -r vyos_cfg_v2/requirements.txt 
#        host: ${{ secrets.PROD_HOST }}
#        username: ${{ secrets.USERNAME }}
#        port: ${{ secrets.PROD_PORT }}
#        password: ${{ secrets.PASSWORD }}
